doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        charset: utf8

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Audit:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Entity'
                prefix: 'Audit\Domain\Entity'
                alias: Audit
